// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezzggoigghunldaeznvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6emdnb2lnZ2h1bmxkYWV6bnZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MzgxODYsImV4cCI6MjA2OTExNDE4Nn0.XfYj8TVzAp7aqD3DvXaL4yTz5VOJ0vCynlcpoUNmTJ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});